version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - ./tmp/data_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

#  app:
#    image: node
#    restart: unless-stopped
#    ports:
#      - "3000:3000"
#    command: npm start ./src/app.js
