version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: DB_USER
      POSTGRES_PASSWORD: DB_PASSWORD
    volumes:
      - ./tmp/data_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  app:
    image: node
    restart: on-failure
    working_dir: /API
    volumes:
      - ./:/API
    ports:
      - "3000:3000"
    command: npm start src/app.js
